"""
Posterior analysis of the 1D Bayesian inference
-----------------------------------------------

All plotting in GeoBIPy can be carried out using the 3D inference class

"""
#%%
import matplotlib.pyplot as plt
from geobipy import example_path
from geobipy import Inference3D
import numpy as np


#%%
# Inference for a single data point
# +++++++++++++++++++++++++++++++++
#
# We can instantiate the inference handler by providing a path to the directory containing
# HDF5 files generated by GeoBIPy.

################################################################################
results_3d = Inference3D(directory=example_path, system_file_path=example_path+"//../../Data")

################################################################################
# We can grab the results for a single index or fiducial
results_1d = results_3d.inference_1d(fiducial=33521.8)

################################################################################
results_1d.plot()
