push-denali:
	rsync -a --exclude=figures --progress . denali-dtn:/caldera/hytest_scratch/scratch/nfoks/geobipy/documentation_source/source/examples/supplementary/data/
pull-denali:
	rsync -a --exclude=figures --progress denali-dtn:/caldera/hytest_scratch/scratch/nfoks/geobipy/documentation_source/source/examples/supplementary/data/ .
push-hw:
	rsync -a --exclude=figures --progress . hovenweep-dtn:/home/nfoks/codes/repositories/geobipy/documentation_source/source/examples/supplementary/data/
pull-hw:
	rsync -a --exclude=figures --progress hovenweep-dtn:/home/nfoks/codes/repositories/geobipy/documentation_source/source/examples/supplementary/data/ .